Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [45]:
n = 8
np.arange(n, -1, -1)

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [46]:
diag_dz = np.diag(np.arange(n, -1, -1))
print(diag_dz)
print(diag_dz.sum())

[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]
36


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [27]:
from numpy import linalg
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

print("x = ", linalg.solve(a, b)[0])
print("y = ", linalg.solve(a, b)[1])
print("z = ", linalg.solve(a, b)[2])




x =  0.4666666666666668
y =  3.844444444444444
z =  -5.555555555555555


Задача 4 

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
На сайт заходит очередной посетитель, о покупках которого известно следующее: next_user_stats = np.array([0, 1, 2, 0, 0, 0])
    Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [44]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

import matplotlib.pyplot as plt

coslist = []

for i in users_stats:
    len_i = np.linalg.norm(i)
    len_new = np.linalg.norm(next_user_stats)
    cos_i = np.dot( i, next_user_stats ) / ( len_i * len_new )
    coslist.append(cos_i)

for n, i in enumerate(users_stats):
    len_i = np.linalg.norm(i)
    len_new = np.linalg.norm(next_user_stats)
    cos_i = np.dot( i, next_user_stats ) / ( len_i * len_new ) 
    if cos_i == max(coslist):
        print("Самый похожий покупатель:", i, ", его номер:", n+1)
    





Самый близкий покупатель: [0 1 1 0 0 0] , его номер: 8
